import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../app/chatgpt-auth';
import {awards,initialBoard,legalMoves,moveBoard,type ArenaGame,type ArenaBoard} from './arena-engine';
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
export function database(){if(!env.DB)throw new ApiError(503,'The live arcade is being connected. Please retry shortly.');return env.DB}
export async function identity(){const user=await getChatGPTUser();if(!user)throw new ApiError(401,'Sign in to join the live arcade.');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(user.userId));const id=Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,'0')).join('');const db=database(),now=Date.now();await db.prepare('INSERT INTO players (id,alias,created,seen) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET seen=excluded.seen WHERE players.seen < ?').bind(id,'Explorer-'+id.slice(0,8).toUpperCase(),now,now,now-15000).run();const p=await db.prepare('SELECT id,alias,qor_id FROM players WHERE id=?').bind(id).first<{id:string;alias:string;qor_id:string|null}>();if(!p)throw new ApiError(503,'Your player profile could not be loaded.');return{id:p.id,name:p.qor_id||p.alias,qorVerified:!!p.qor_id}}
export function sameOrigin(req:Request){const origin=req.headers.get('Origin');if(!origin||origin!==new URL(req.url).origin)throw new ApiError(403,'This request must come from the arcade.');if(!req.headers.get('Content-Type')?.startsWith('application/json'))throw new ApiError(415,'JSON required.')}
export async function body(req:Request){sameOrigin(req);if(Number(req.headers.get('Content-Length')||0)>4096)throw new ApiError(413,'Request is too large.');const raw=await req.text();if(raw.length>4096)throw new ApiError(413,'Request is too large.');try{return JSON.parse(raw) as Record<string,unknown>}catch{throw new ApiError(400,'Invalid request.')}}
export function response(value:unknown,status=200){return Response.json(value,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
export async function api(fn:()=>Promise<Response>){try{return await fn()}catch(e){if(e instanceof ApiError)return response({error:e.message},e.status);console.error('Arcade request failed:',e instanceof Error?e.message:'unknown');return response({error:'The live connection is temporarily unavailable. Your last saved state is safe.'},503)}}
export function gameType(value:unknown):ArenaGame{if(value!=='flux'&&value!=='reversi')throw new ApiError(400,'Choose Flux Four or Rift Reversi.');return value}
export type Match={id:string;game:ArenaGame;host:string;guest:string|null;status:string;board:string;turn:number;winner:number|null;moves:number;revision:number;created:number;updated:number;deadline:number;last_action:string|null;settled:number};
export async function getMatch(id:string){if(!/^[0-9a-f-]{36}$/.test(id))throw new ApiError(400,'Invalid match code.');const m=await database().prepare('SELECT * FROM matches WHERE id=?').bind(id).first<Match>();if(!m)throw new ApiError(404,'This match could not be found.');return m}
export async function snapshot(m:Match,me:string){const rows=await database().prepare('SELECT id,alias,qor_id FROM players WHERE id IN (?,?)').bind(m.host,m.guest||'').all<{id:string;alias:string;qor_id:string|null}>();const player=(id:string|null)=>{const p=rows.results.find(p=>p.id===id);return p?{id:p.id,name:p.qor_id||p.alias,qorVerified:!!p.qor_id}:null};const state=JSON.parse(m.board) as ArenaBoard;return{id:m.id,game:m.game,status:m.status,state,revision:m.revision,moves:m.moves,deadline:m.deadline,serverNow:Date.now(),host:player(m.host),guest:player(m.guest),seat:m.host===me?1:m.guest===me?2:0,legal:m.status==='active'?legalMoves(m.game,state):[]}}
export async function saveMove(m:Match,state:ArenaBoard,moves:number){const db=database(),now=Date.now(),token=crypto.randomUUID(),done=state.winner!==null,status=done?'done':'active';const statements=[db.prepare('UPDATE matches SET board=?,turn=?,winner=?,moves=?,status=?,revision=revision+1,updated=?,deadline=?,last_action=? WHERE id=? AND revision=? AND status=\'active\'').bind(JSON.stringify(state),state.turn,state.winner,moves,status,now,now+90000,token,m.id,m.revision)];if(done&&m.guest){for(const [id,seat]of[[m.host,1],[m.guest,2]] as const){const a=awards(state.winner!,seat,moves);statements.push(db.prepare('INSERT INTO standings (player,game,wins,losses,draws,points,updated) SELECT ?,?,?,?,?,?,? FROM matches WHERE id=? AND last_action=? AND settled=0 AND moves>=6 ON CONFLICT(player,game) DO UPDATE SET wins=standings.wins+excluded.wins,losses=standings.losses+excluded.losses,draws=standings.draws+excluded.draws,points=standings.points+excluded.points,updated=excluded.updated').bind(id,m.game,a.wins,a.losses,a.draws,a.points,now,m.id,token))}statements.push(db.prepare('UPDATE matches SET settled=1 WHERE id=? AND last_action=? AND settled=0').bind(m.id,token))}const result=await db.batch(statements);if(!result[0].meta.changes)throw new ApiError(409,'The board has changed. Your latest match is being refreshed.');return getMatch(m.id)}
export async function expire(m:Match){if(m.status==='active'&&m.deadline<Date.now()){const state=JSON.parse(m.board) as ArenaBoard;try{return await saveMove(m,{...state,winner:3-state.turn},m.moves)}catch(e){if(e instanceof ApiError&&e.status===409)return getMatch(m.id);throw e}}return m}
export async function createMatch(player:string,game:ArenaGame){const db=database(),now=Date.now(),id=crypto.randomUUID();const r=await db.prepare('INSERT INTO matches (id,game,host,status,board,turn,created,updated,deadline) SELECT ?,?,?,\'waiting\',?,1,?,?,? WHERE (SELECT COUNT(*) FROM matches WHERE host=? AND created>?)<5 AND (SELECT COUNT(*) FROM matches WHERE (host=? OR guest=?) AND status IN (\'waiting\',\'active\') AND updated>?)<3').bind(id,game,player,JSON.stringify(initialBoard(game)),now,now,now+900000,player,now-60000,player,player,now-900000).run();if(!r.meta.changes)throw new ApiError(429,'Finish or close an existing match before creating another.');return getMatch(id)}
export async function actionMatch(m:Match,player:string,action:unknown,cell:unknown,revision:unknown){const db=database(),now=Date.now();if(action==='join'){if(m.host===player)throw new ApiError(400,'A second player must join this match.');const r=await db.prepare('UPDATE matches SET guest=?,status=\'active\',updated=?,deadline=?,revision=revision+1 WHERE id=? AND guest IS NULL AND status=\'waiting\' AND deadline>?').bind(player,now,now+90000,m.id,now).run();if(!r.meta.changes)throw new ApiError(409,'This lobby is no longer available.');return getMatch(m.id)}const seat=m.host===player?1:m.guest===player?2:0;if(!seat)throw new ApiError(403,'Only the match players can make moves.');if(action==='cancel'&&m.status==='waiting'){await db.prepare('UPDATE matches SET status=\'cancelled\',revision=revision+1 WHERE id=? AND host=? AND status=\'waiting\'').bind(m.id,player).run();return getMatch(m.id)}if(m.status!=='active')throw new ApiError(409,'This match is not active.');if(revision!==m.revision)throw new ApiError(409,'The board has changed. Refreshing the match.');m=await expire(m);if(m.status!=='active')return m;const state=JSON.parse(m.board) as ArenaBoard;if(action==='resign')return saveMove(m,{...state,winner:3-seat},m.moves);if(action!=='move'||state.turn!==seat)throw new ApiError(400,'Wait for your turn.');if(typeof cell!=='number'||!Number.isInteger(cell))throw new ApiError(400,'Choose a valid cell.');let next:ArenaBoard;try{next=moveBoard(m.game,state,cell)}catch(e){throw new ApiError(400,(e as Error).message)}return saveMove(m,next,m.moves+1)}
