import {sqliteTable,text,integer,index,primaryKey,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const players=sqliteTable('players',{id:text('id').primaryKey(),alias:text('alias').notNull(),qorId:text('qor_id'),created:integer('created').notNull(),seen:integer('seen').notNull(),lastChat:integer('last_chat').notNull().default(0),chatGate:text('chat_gate')},t=>[index('players_seen_idx').on(t.seen),uniqueIndex('players_qor_idx').on(t.qorId)]);
export const matches=sqliteTable('matches',{id:text('id').primaryKey(),game:text('game').notNull(),host:text('host').notNull().references(()=>players.id),guest:text('guest').references(()=>players.id),status:text('status').notNull(),board:text('board').notNull(),turn:integer('turn').notNull(),winner:integer('winner'),moves:integer('moves').notNull().default(0),revision:integer('revision').notNull().default(0),created:integer('created').notNull(),updated:integer('updated').notNull(),deadline:integer('deadline').notNull(),lastAction:text('last_action'),settled:integer('settled').notNull().default(0)},t=>[index('matches_status_created_idx').on(t.status,t.created),index('matches_host_status_idx').on(t.host,t.status),index('matches_guest_status_idx').on(t.guest,t.status)]);
export const standings=sqliteTable('standings',{player:text('player').notNull().references(()=>players.id),game:text('game').notNull(),wins:integer('wins').notNull().default(0),losses:integer('losses').notNull().default(0),draws:integer('draws').notNull().default(0),points:integer('points').notNull().default(0),updated:integer('updated').notNull()},t=>[primaryKey({columns:[t.player,t.game]}),index('standings_game_points_idx').on(t.game,t.points)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),player:text('player').notNull().references(()=>players.id),body:text('body').notNull(),created:integer('created').notNull(),deleted:integer('deleted').notNull().default(0)},t=>[index('messages_created_idx').on(t.created)]);
export const reports=sqliteTable('reports',{message:text('message').notNull().references(()=>messages.id),player:text('player').notNull().references(()=>players.id),reason:text('reason').notNull(),created:integer('created').notNull()},t=>[primaryKey({columns:[t.message,t.player]})]);
// QOR ID sign-in (P7.3): a pending sign-in, single use for ten minutes, and a signed-in session whose
// id is the SHA-256 of the browser's cookie, never the cookie itself.
export const qorLogins=sqliteTable('qor_logins',{state:text('state').primaryKey(),verifier:text('verifier').notNull(),created:integer('created').notNull()},t=>[index('qor_logins_created_idx').on(t.created)]);
export const qorSessions=sqliteTable('qor_sessions',{id:text('id').primaryKey(),sub:text('sub').notNull(),qorId:text('qor_id').notNull(),username:text('username').notNull(),chainAccount:text('chain_account'),accessToken:text('access_token').notNull(),refreshToken:text('refresh_token').notNull(),created:integer('created').notNull(),expires:integer('expires').notNull()},t=>[index('qor_sessions_expires_idx').on(t.expires),index('qor_sessions_sub_idx').on(t.sub)]);
